<?xml version="1.0" encoding="utf-8"?><Database Name="StillKickingMe_db" Class="StillKickingDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=boilermake.database.windows.net;Initial Catalog=StillKickingMe_db;User ID=Boilermake" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StillKickingMe_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Caregiver" Member="Caregivers">
    <Type Name="Caregiver">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactType_IDFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Patient_IDFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactType" Member="ContactTypes">
    <Type Name="ContactType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmergencyContact" Member="EmergencyContacts">
    <Type Name="EmergencyContact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Patient_IDFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Event_Type_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event_Type" Member="Event_Types">
    <Type Name="Event_Type">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Medical Condition]" Member="Medical_Conditions">
    <Type Name="Medical_Condition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Patient_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalInfo" Member="MedicalInfos">
    <Type Name="MedicalInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="History" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medication" Member="Medications">
    <Type Name="Medication">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserIDFK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="pills_to_take" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eat_with_food" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dosage_mg" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="repeat_hours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="repeat_start" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient_Caregiver_rel" Member="Patient_Caregiver_rels">
    <Type Name="Patient_Caregiver_rel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Caregiver_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient_Medication_rel" Member="Patient_Medication_rels">
    <Type Name="Patient_Medication_rel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Medication_IDFK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="to_take" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_to_take" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="week_repeat_code" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="severity" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>